@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Entry {
    task
    urgency
    green space
}

class Team{
    collaborators
}

class Collaborators{
    name
    birthdate
    admission date
    address
    contact info (mobile and email)
    ID doc type
    ID number
}

Collaborators "2..*"-- "1"Team : make >
Entry "1..*" -- "1" Team : attributed to

@enduml