@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Entry {
    task
    urgency
    green space
    team
}

class Team{
    collaborators
}




class Agenda {
    task description
    date
}




class Organization {}

Organization "1" -down- "1..*" Employees : has >
Organization "1" - "1" Team : creates
Employees "1" -"1..*" Managers : are >
Managers "1" -down- "1" Agenda: manages >
Agenda "1" - "1..*" Entry : contains >
Entry "1..*" -- "1" Team : attributed to <


@enduml