@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Skills {
    - String description

    + Skills(description)
}

class Manager {
    - String name
    - String role
    - String phone
    - String email

    + anyEmployeeHasEmail(email)
    + Manager(name, role, phone, email, postalAddress, manager)
    + createSkill()
}

class SkillsRepository {
    + getSkills()
}

class EmployeeRepository {
    + getOrganizationByEmployeeEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobsRepository()
    + getEmployeeRepository()
}

class RegisterSkillsController {
    + RegisterSkillsController(employeeRepository, SkillsRepository)
    + getJobList()
    + createJob(skills needed)
}

note bottom of SkillsRepository
    - used for accessing
    the skills
end note

class RegisterSkillsUI {
}

Repositories -> Repositories : instance

RegisterSkillsUI .> RegisterSkillsController

RegisterSkillsController .> Repositories : repositories

Repositories -> "1" SkillsRepository

RegisterSkillsController ..> Skills : jobs
RegisterSkillsController ..> EmployeeRepository : employeeRepository


Repositories --> "1" EmployeeRepository

EmployeeRepository --> "*" Manager

RegisterSkillsController ..> "1" Manager : manager
SkillsRepository "1" --> "*" Skills : jobs
Manager "1" --> "1..*" Skills : register

@enduml