@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
title System Sequence Diagram (SSD) - Alternative One
autonumber
actor "HRM" as HRM
participant ":System" as System
activate HRM
    HRM -> System : asks to register an employee with a profession and key attributes
    activate System
        System --> HRM : requests data (an employee)
    HRM -> System : types requested data (an employee)
    deactivate System
        System -> HRM : asks to select a set of skills
        activate System
    HRM -> System : selects the intended skills
    deactivate System
    System -> HRM : ask to select a job
       activate System
    HRM -> System : selects the intended job
    deactivate System
           System --> HRM : displays all data and operation success
   activate System
        System --> HRM : displays operation success
   deactivate System
deactivate HRM
@enduml