@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "HRM" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to register an employee with a profession and key attributes
    activate System
        System --> HRM : requests data (an employee)
    deactivate System
    HRM -> System : types requested data (an employee)
     activate System
    System -> HRM : asks to select a set of skills
    deactivate System
    HRM -> System : selects the intended skills
   activate System
    System -> HRM : ask to select a job
    deactivate System
    HRM -> System : selects the intended job
        activate System
        System --> HRM : shows all data and displays operation success
    deactivate System



@enduml