@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

class List_Vehicles {
}

class Vehicle{
 Brand
  Model
  Type
  Tara
  CurrentKm
  RegisterDate
}

class FleetManager {
}

class CheckUp {
  Date
}

class Managers {
    name
    email
    position
    phone
}

Managers "1" -- "1" FleetManager : have >
Managers "1" -- "0..*" List_Vehicles : wants >
Vehicle "1" -- "1" CheckUp : needing >
List_Vehicles "1" -- "0..*" Vehicle : has >
@enduml


