@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods


class Vehicles_Machines_Equipment{
 Brand
  Model
  Type
  Tara
  CurrentKm
  RegisterDate
}

class FleetManager {
}

class CheckUp {
  Date
}

class Managers {
    name
    email
    position
    phone
}

Managers "1" -- "1" FleetManager : have >
Vehicles_Machines_Equipment "1" -- "1" CheckUp : needs >
Managers "1" -- "1..*" Vehicles_Machines_Equipment : lists >
@enduml


