@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as VFM
participant ":VehiclesNeedingCheckUpUI" as UI
participant ":VehiclesNeedingCheckUpController" as CTRL
participant "Repositories" as Rep
participant "repositories:\nRepositories" as Repositories
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "vehicle:\nVehicle" as Vehicle

activate VFM

VFM -> UI : Request to list vehicles needing check-up

    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getVehiclesNeedingCheckUp()
        activate CTRL

            CTRL -> Rep : getInstance()
            activate Rep

                Rep --> CTRL : repositories
            deactivate Rep

            CTRL -> Repositories : getVehicleRepository()
            activate Repositories

            Repositories --> CTRL : VehicleRepository
            deactivate Repositories


            CTRL -> VehicleRepository : getVehicles()
            activate VehicleRepository

                VehicleRepository --> CTRL : Vehicles
            deactivate VehicleRepository


            CTRL --> UI : VehiclesNeedingCheckUp
        deactivate CTRL

        UI --> VFM : Shows list of vehicles needing check-up

    deactivate UI

deactivate VFM

@enduml
