@startuml

class AssignTeamToEntryController {
    -teamRepository: TeamRepository
    +AssignTeamToEntryController()
    +getTeams(): List<Team>
    +getTeams(index: int): Team
    -getTeamRepository(): TeamRepository
}

class AssignTeamToEntryUI {

}


class TeamRepository {
    -teams: List<Team>
    +TeamRepository()
    +getInstance(): TeamRepository
    +getTeams(): List<Team>
    +getTeams(index: int): Team
}

class Repositories {
    +getInstance(): Repositories
    +getTeamRepository(): TeamRepository
}

class AgendaRepository {
    -entries: List<Entry>
    +getEntries(): List<Entry>
    +getEntries(index: int): Entry
}

class Entry {
    -team: Team
    +setTeam(team: Team)
}
class Organization {
}
class OrganizationRepository{
}

AssignTeamToEntryController "1" .> "1" Repositories : Repositories
AssignTeamToEntryUI .>  AssignTeamToEntryController
Repositories "1" --> "1" TeamRepository : TeamRepository
Repositories "1" -> "1" AgendaRepository : AgendaRepository
TeamRepository "1" --> "1" Organization
Repositories --> OrganizationRepository
OrganizationRepository "1" --> "1" Organization
AgendaRepository "1" --> "1" Organization
Repositories -> Repositories : Instance
Organization "1" --> "*" Entry
AssignTeamToEntryController "1" -> "1" Organization


@enduml