@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager" as GSM
participant ":AssignTeamToEntryUI" as UI
participant ":AssignTeamToEntryCTRL" as CTRL
participant "repositories:\nRepositories" as Repositories
participant "repositories"
participant "teamRepository:\nTeamRepository" as TeamRepository
participant "agendaRepository:\nAgendaRepository" as AgendaRepository
participant "organization:\nOrganization" as Org
participant "organizationRepository:\nOrganizationRepository" as OrgRepository
participant "team:\nTeam" as Team
participant "entry:\nEntry" as Entry
participant "EmailSenderInterface" as EmailSender
participant "mailer:\nMailer" as Mailer
participant "config.properties" as Config

activate GSM
    GSM -> UI : Wants to assign team to entry
    activate UI
        UI --> CTRL** : create
        UI -> CTRL : getTeams()
        activate CTRL
            CTRL -> Repositories : getInstance()
            activate Repositories
            Repositories -> CTRL : repositories
            deactivate Repositories
            CTRL -> repositories : getTeamRepository()
            activate repositories
            repositories --> CTRL : TeamRepository
            deactivate repositories
            CTRL -> TeamRepository : getTeams()
                activate TeamRepository
                    TeamRepository --> CTRL : Teams
                deactivate TeamRepository
        CTRL --> UI : Teams
        deactivate CTRL
        UI -> GSM : shows teams
        deactivate UI
        GSM -> UI : selects team
        activate UI
        UI --> UI : keepTeam(selectedTeam)

        UI -> CTRL : getEntries()

      activate CTRL
                  CTRL -> repositories : getAgendaRepository()
                  activate repositories
                  repositories --> CTRL : AgendaRepository
                  deactivate repositories
                  CTRL -> AgendaRepository : getEntries()
                      activate AgendaRepository
                          AgendaRepository --> CTRL : Entries
                      deactivate AgendaRepository


              CTRL --> UI : Entries
              deactivate CTRL

        UI -> GSM : shows entries
        deactivate UI
        GSM -> UI : selects entry
        activate UI
        UI --> UI : keepEntry(selectedEntry)
        UI -> CTRL : attributeTeamToEntry(selectedTeam, selectedEntry)
        activate CTRL
            CTRL -> repositories : getOrganizationRepository()
                activate repositories
                repositories --> CTRL : OrganizationRepository
                deactivate repositories
            CTRL -> OrgRepository : getOrganization()
                activate OrgRepository
                    OrgRepository --> CTRL : Organization
                deactivate OrgRepository


            CTRL -> Org : setTeam(selectedTeam)
            activate Org
            Org --> Entry : setTeam(selectedTeam)
            deactivate Org
            activate Entry
            Entry --> CTRL : Entry updatedEntry
            deactivate Entry

            CTRL -> EmailSender : sendEmail(updatedEntry)
            activate EmailSender
            EmailSender -> Mailer : sendEmail(updatedEntry)
            deactivate EmailSender
            activate Mailer
                Mailer -> Config : getProperties()
                activate Config
                    Config --> Mailer : properties
                deactivate Config
                Mailer --> CTRL : (In)Success of email
            deactivate Mailer

        CTRL --> UI : (In)Success and updatedEntry

        deactivate CTRL

        UI-> GSM : Displays (In)Success and updatedEntry
    deactivate UI
deactivate GSM
@enduml