@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox
participant RegisterJobUI as UI
participant RegisterJobController as CTRL
participant JobRepository as jobRepository
participant Job as job
participant Repositories as PLAT


-> UI: types requested data
activate UI

    group Job registration
        UI --> UI: validateJob(Job job)
    end
    <-- UI : displays operation success
deactivate CTRL

@enduml