@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Request to register vehicles check-up result
    activate System

        System --> Employee : Display vehicle selection interface
    deactivate System

    Employee -> System : Select vehicle
    activate System

        System --> Employee : Display Vehicle details
    deactivate System

    Employee -> System : Registers results
    activate System

        System --> Employee :  Confirmation of results registration
    deactivate System

@enduml