@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":RegisterResultUI" as UI
participant ":RegisterResultController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "VehicleDetails:\n vehicleDetails" as VehicleDetails
participant "checkUp:\n CheckUp" as CheckUp
activate ADM

        ADM -> UI : Request to register vehicles check-up result

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getVehicleList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: VehicleRepository
                deactivate PLAT
                loop
                    CTRL -> VehicleRepository : getVehicle()
                    activate VehicleRepository

                        VehicleRepository -> CheckUp :getVehicle()
                            activate CheckUp

                            CheckUp -> VehicleRepository :Vehicle
                            deactivate CheckUp
                        VehicleRepository --> CTRL : Vehicle
                    deactivate VehicleRepository
                end

                CTRL --> UI : VehicleList
            deactivate CTRL

            UI --> ADM : Display vehicle selection interface
        deactivate UI

    ADM -> UI : Select vehicle
    activate UI

        UI -> CTRL : getVehicleDetails()
        activate CTRL

            CTRL -> VehicleDetails : getVehicleDetails()
            activate VehicleDetails

                VehicleDetails --> CTRL : VehicleDetails
            deactivate VehicleDetails

        CTRL --> UI : VehicleDetails
        deactivate CTRL
        UI --> ADM : Display Vehicle details
    deactivate UI

    ADM -> UI : Registers results
    activate UI

        UI -> CheckUp : registResult()
        activate CheckUp

        CheckUp --> UI : Result
        deactivate CheckUp
        UI --> ADM : Confirmation of results registration
    deactivate UI



deactivate ADM

@enduml