@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Request to list vehicles needing check-up
    activate System

        System --> Employee : Retrieve list of vehicles needing check-up
    deactivate System

    Employee -> System : Verifies the vehicle's information
    activate System

        System --> Employee : Sends a message indicating that the process has been terminated
    deactivate System
@enduml