@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Requests to register a vehicle
    activate System

        System --> Employee : Requests data
    deactivate System

    Employee -> System : Types requested data(brand, model, check-up frequency, vehicleID, type, tare, grossWeight, currentKm, registerDate, acquisitionDate)
    activate System

        System --> Employee : Display the vehicle that has been created
    deactivate System

    Employee -> System : Confirms data
    activate System

        System --> Employee : Displays success message
    deactivate System



@enduml