@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class VehicleNeedingCheckUpUI{

}

class VehicleNeedingCheckUpController{
    -vehicleRepository: VehicleRepository
    -authenticationRepository: AuthenticationRepository
    +VehicleNeedingCheckUpController(vehicleRepository: VehicleRepository, authenticationRepository: AuthenticationRepository)
    +getVehicleRepository(): VehicleRepository
    +getVehiclesNeedingCheckUp(): List<Vehicle>
    +getAuthenticationRepository(): AuthenticationRepository
}

class Repositories{
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}

class VehicleRepository{
    -vehicles: List<Vehicle>
    +getVehicles(): List<Vehicle>
}

class Vehicle{
    -currentKm: double
    -checkUpFrequency: double
    -lastMaintenanceKm: double
    +Vehicle(brand: String, model: String, tareWeight: double, \ngrossWeight: double, currentKm: double, registerDate: LocalDate, \nacquisitionDate: LocalDate, checkUpFrequency: double)
    +getLastMaintenanceKm(): double
    +getCurrentKm(): double
    +getCheckUpFrequency(): double
}

VehicleNeedingCheckUpUI .> VehicleNeedingCheckUpController
VehicleNeedingCheckUpController ..> Repositories : repositories
Repositories -> "1" VehicleRepository
VehicleNeedingCheckUpController ..> VehicleRepository : vehicleRepository
VehicleRepository "1" --> "1*" Vehicle : vehicle

@enduml