@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as VFM
participant ":VehiclesNeedingCheckUpUI" as UI
participant ":VehiclesNeedingCheckUpController" as CTRL

activate VFM

VFM -> UI : Request to list vehicles needing check-up

    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getVehiclesNeedingCheckUp()

        ref over CTRL
                            Get Vehicles
                        end

        activate CTRL

            CTRL --> UI : VehiclesNeedingCheckUp
        deactivate CTRL

        UI --> VFM : Shows list of vehicles needing check-up

    deactivate UI

deactivate VFM

@enduml