@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Consult Assigned Tasks Between Two Dates

autonumber

actor "Collaborator" as Collaborator
participant ":System" as System

activate Collaborator

    Collaborator -> System : Requests to consult tasks
    activate System

        System --> Collaborator : Asks for date interval
    deactivate System

    Collaborator -> System : Types date interval
    activate System

        System --> Collaborator : Retrieves tasks list
    deactivate System

@enduml
