@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List All Managed Green Spaces

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Request to list all managed green spaces
    activate System

        System --> Employee : Retrieve list of green spaces
    deactivate System

    Employee -> System : Chooses green spaces managed by GSM
    activate System

        System --> Employee : Confirmation of the operation
    deactivate System

    Employee -> System : Confirms that he want to creat the list
        activate System

            System --> Employee : Show the list
        deactivate System

@enduml
