@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List All Managed Green Spaces

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Request to list all green spaces managed by him
    activate System

        System --> Employee : Retrieves list of green spaces managed by the GSM
    deactivate System

    Employee -> System : Confirms that he want to creat the list
        activate System

            System --> Employee : Show the list
        deactivate System

@enduml
