@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as VFM
participant ":ListTaskSpaceUI" as UI
participant ":ListTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "taskRepository\n:TaskRepository" as taskRepository
participant "statusList\n:List<String>" as LISTSTATUS


activate VFM

VFM -> UI : Requests to consult tasks between two dates

    activate UI

        UI -> CTRL** : create

        UI --> VFM : Retrieves Collaborators list


        UI -> CTRL :
        activate CTRL

        CTRL -> UI :
        deactivate CTRL


VFM -> UI : Chooses a Collaborator

 UI -> CTRL : getCollaboratorThoughEmail(email)
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getCollaboratorRepository
            activate REP

            REP --> CTRL : collaboratorRepository
            deactivate REP

        CTRL -> collaboratorRepository : getCollaboratorThoughEmail(email)
            activate collaboratorRepository



            collaboratorRepository --> CTRL : collaborator

                deactivate collaboratorRepository

            deactivate collaboratorRepository
        CTRL --> UI : collaborator
        deactivate CTRL
UI --> VFM : Asks for date interval


VFM -> UI : Types date interval


    UI -> CTRL : getStatusList()
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getTaskRepository()
            activate REP

            REP --> CTRL : taskRepository
            deactivate REP

        CTRL -> taskRepository : getStatusList()
            activate taskRepository

            taskRepository --> LISTSTATUS** : create()


            deactivate LISTSTATUS

        taskRepository --> CTRL : statusList
        deactivate taskRepository

        CTRL --> UI : statusList
        deactivate CTRL

UI --> VFM : Retrieves tasks list


    deactivate UI

deactivate VFM

@enduml
