@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ListTaskSpaceUI{

}


class ListTaskController{
   + create()
       + getCollaboratorThoughEmail(email)
       + getStatusList()
       + getTaskList(collaborator, dateI, dateF, typeStatus)
}


class Repositories{
    - Repositories()
        + getInstance(): Repositories
        + getCollaboratorRepository(): CollaboratorRepository
        + getTaskRepository(): TaskRepository
        + getTeamRepository(): TeamRepository
        + getAgenda(): Agenda
}

class TaskRepository{
    - List<Task> taskList
    - List<String> statusList
    + getStatusList()
    + getTaskList(teamList, dateI, dateF, typeStatus)
    + addTaskOfCollaborator(task)
}

class CollaboratorRepository{
    + getCollaboratorThoughEmail(email))
}

class TeamRepository{
    + getTeamsThoughCollaborator(collaborator)
}

class Agenda{
    +getCollaboratorAgendaEntries(taskList)
}

class ToDoList{
    -List<ToDoList> toDoListEntries
    +getStatusList()
}




ListTaskSpaceUI .> ListTaskController
ListTaskController..> Repositories : repositories
Repositories -> "1" TaskRepository
ListTaskController ..> TaskRepository : getTaskRepository
ListTaskController..> CollaboratorRepository
ListTaskController..> TeamRepository

@enduml