@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class TaskAssignedToCollaboratorUI{

}

class TaskAssignedToCollaboratorController{

}

class Organization{

}

class OrganizationRepository{

}

class Agenda{

}

class Repositories{

}

class Entry{

}

TaskAssignedToCollaboratorUI .> TaskAssignedToCollaboratorController
TaskAssignedToCollaboratorController ..> Organization
TaskAssignedToCollaboratorController .> Repositories
Repositories --> OrganizationRepository
Repositories --> Agenda
OrganizationRepository --> Organization
Agenda --> Organization
Organization --> Entry

@enduml