@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as EMP
participant ":TaskAssignedToCollaboratorUI" as UI
participant ":TaskAssignedToCollaboratorController" as CTRL

activate EMP

    EMP -> UI : Requests to consult tasks
    activate UI

        UI --> EMP : Asks for date interval and status of the task
    deactivate UI

    EMP -> UI : Types date interval and status of the task
    activate UI

        UI -> CTRL** : create

            UI -> CTRL : verifyEntries()
            activate CTRL

                ref over CTRL
                    Get Entries
                end

                CTRL --> UI : entries
            deactivate CTRL

        UI --> EMP : Retrieves tasks list
    deactivate UI



@enduml
