@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as VFM
participant ":CheckupListUI" as UI
participant ":CheckupListController" as CTRL
participant "Repositories" as Rep
participant "repositories:\nRepositories" as Repositories
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "vehicle:\nVehicle" as Vehicle

activate VFM

VFM -> UI : Request to list vehicles needing check-up

    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getCheckUpList()
        activate CTRL

            CTRL -> Rep : getInstance()
            activate Rep

                Rep --> CTRL : repositories
            deactivate Rep

            CTRL -> Repositories : getVehicleRepository()
            activate Repositories

            Repositories --> CTRL : VehicleRepository
            deactivate Repositories

            loop
                CTRL -> VehicleRepository : getVehicle()
                activate VehicleRepository

                    VehicleRepository -> Vehicle : getVehicleKm()
                    activate Vehicle

                    Vehicle --> VehicleRepository : VehicleKm
                    deactivate Vehicle

                    VehicleRepository --> CTRL : Vehicle
                deactivate VehicleRepository
            end

            CTRL --> UI : CheckUpList
        deactivate CTRL

        UI --> VFM : Shows list of vehicles needing check-up

        deactivate UI
        VFM -> UI : Verifies the details of a vehicle
        activate UI

        UI -> CTRL : getVehicleDetails()
        activate CTRL

            CTRL -> Rep : getInstance()
            activate Rep

                Rep --> CTRL : repositories
            deactivate Rep
            CTRL -> Repositories : getVehicleRepository()
            activate Repositories

                Repositories --> CTRL : VehicleRepository
            deactivate Repositories

            CTRL -> Vehicle : getVehicleDetails()
            activate Vehicle

                Vehicle --> CTRL : Vehicle
            deactivate Vehicle
            CTRL --> UI : Vehicle
        deactivate CTRL
        UI --> VFM : Shows vehicle details
    deactivate UI

@enduml
