@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods
class Outside_User{
    name
    email
    password
}
class Portal{
    task category
}
class Malfunctions{}
class Flaws{}
class Comments{}
class Agenda{
    tasks
}
class Garden{
    description
}
class Medium_Sized{
    description
}
class Large_Sized{
    description
}
class Vehicles_Machines_Equipment{
    description
}
class VFM{}
class HRM{}
class GSM{}
class Green_Spaces{

}
class Team{
    collaborators
}

class Collaborators{
    name
    birthdate
    admission date
    address
    contact info (mobile and email)
    ID doc type
    ID number
}
class Employees {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Task {
    reference
    description
    informalDesc
    technicalDesc
    duration
    cost
}
class Managers {
    name
    email
    position
    phone
}
class Organization{}
class CheckUp{
    date
}
class Skill{}
class Jobs{}

Organization "1" - "1..*" Employees : has >
Organization "1"- "1..*"Vehicles_Machines_Equipment: has >
Employees "1" -- "*" Collaborators: are >
Employees "1" -- "*" Managers : are >
Managers "1" -- "1"GSM: has >
Managers "1" -- "1"HRM: has >
Managers "1" -- "1"VFM: has >
Managers "1" -- "1..*"Team: creates >
Managers "1"-- "1..*"Green_Spaces: manages >
Managers "1"-- "*"Collaborators: hire and register >
Managers "1"-- "*"Vehicles_Machines_Equipment: choose and register >
Managers "1" -- "1..*" Skill: register >
Managers "1" -- "1..*" Jobs: register >
Skill "1..*" -- "1"Collaborators: attributed to >
Jobs "1" -- "1"Collaborators: given to >
Vehicles_Machines_Equipment "*" -- "1"Team: are attributed to >
Vehicles_Machines_Equipment "*" -- "1" CheckUp: need >
Agenda "1" -- Managers: is managed by >
Green_Spaces"1" -- "*" Garden: has >
Green_Spaces "1" -- "*" Medium_Sized: has >
Green_Spaces "1" -- "*" Large_Sized: has >
Green_Spaces "1..*" -- "*" Task: originates >
Collaborators "2..*"-- "1"Team : make >
Team"1" -- "1..*"Task : attributed <
Task "1..*"-- "1" Green_Spaces: solved in >
Task "*" -- "1"Agenda : goes to >
Portal "1" -- "*"Malfunctions: receives >
Portal "1" -- "*"Flaws: receives >
Portal "1" -- "*"Comments: receives >
Outside_User "1" -- "1" Portal : reports to >
Outside_User "*" -- "1..*"Green_Spaces: use >
Malfunctions "*"-- "*"Task: creates >
Flaws "*" -- "*" Task : creates >
Managers "1" -- "1" CheckUp: register >
CheckUp "1" -- "1" Vehicles_Machines_Equipment: has >

@enduml