@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant "RegisterGreenSpaceUI" as UI
participant "RegisterGreenSpaceController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as organizationRepository
participant "greenSpace: \n GreenSpace" as GreenSpace
participant "greenSpaceRepository: \n GreenSpaceRepository" as GreenSpaceRep

activate GSM

     GSM -> UI : asks to register a new GreenSpace

     activate UI

            UI -> GSM : requests a name
            GSM -> UI : types name
            UI -> GSM : request size
            GSM -> UI : selects size
            UI -> GSM : requests area
            GSM -> UI : types area
            UI -> CTRL** : create


     activate CTRL

            CTRL -> Rep : getInstance()

     activate Rep

            Rep -> CTRL : repositories

     deactivate Rep

            CTRL -> organizationRepository : getOrganizationRepository()

     activate organizationRepository

            organizationRepository -> CTRL : organizationRepository

     deactivate organizationRepository

            CTRL -> GreenSpace : registerGreenSpace(name, area, size, managerName)

     activate GreenSpace

            GreenSpace -> GreenSpaceRep : addGreenSpace(GreenSpace greenSpace)

     activate GreenSpaceRep

            GreenSpaceRep -> GreenSpace : greenSpace

     deactivate GreenSpaceRep

            GreenSpace -> CTRL : greenSpace

     deactivate GreenSpace

            CTRL -> UI : greenSpace

     deactivate CTRL

     UI --> GSM : displays all data and operation success

     deactivate UI

@enduml
