@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant "RegisterGreenSpaceUI" as UI
participant "RegisterGreenSpaceController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as organizationRepository
participant "greenSpace: \n GreenSpace" as GreenSpace
participant "Size" as Size

activate GSM

     GSM -> UI : asks to register a new GreenSpace

     activate UI

            UI -> GSM : requests data (manager's name)
            GSM -> UI : types requested data (manager's name)
            UI -> GSM : requests data (Green Space name)
            GSM -> UI : types requested data (Green Space name)
            UI -> CTRL** : create
            activate CTRL
            CTRL -> Size : getSize()
            activate Size
            Size -> CTRL : size
            deactivate Size
            CTRL -> UI : size

            UI -> GSM : request size
            GSM -> UI : selects size
            UI -> GSM : requests area
            GSM -> UI : types area


            CTRL -> Rep : getInstance()

     activate Rep

            Rep -> CTRL : repositories

     deactivate Rep

            CTRL -> organizationRepository : getOrganizationRepository()

     activate organizationRepository

            organizationRepository -> CTRL : organizationRepository

     deactivate organizationRepository

            CTRL -> GreenSpace : registerGreenSpace(name, area, size, managerName)

     activate GreenSpace

            GreenSpace -> CTRL : greenSpace

     deactivate GreenSpace

            CTRL -> UI : greenSpace

     deactivate CTRL

     UI --> GSM : displays all data and operation success

     deactivate UI

@enduml