@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant "RegisterGreenSpaceUI" as UI
participant "RegisterGreenSpaceController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as organizationRepository
participant "organization:\n Organization" as Organization
participant "greenSpace: \n GreenSpace" as GreenSpace

activate GSM

     GSM -> UI : asks to register a new GreenSpace

     activate UI

            UI -> GSM : requests a name
            GSM -> UI : types name
            UI -> GSM : request size
            GSM -> UI : selects size
            UI -> GSM : requests area
            GSM -> UI : types area
            UI -> CTRL : creates


     activate CTRL

            CTRL -> Rep : getInstance()

     activate Rep

            Rep -> CTRL : repositories

     deactivate Rep

            CTRL -> organizationRepository : getOrganizationRepository()

     activate organizationRepository

            organizationRepository -> CTRL : organizationRepository

     deactivate organizationRepository

            CTRL -> Organization : getManager()

     activate Organization

            Organization -> CTRL : Manager

     deactivate Organization

            CTRL -> GreenSpace : GreenSpace(name, area, size, email)

     activate GreenSpace

            GreenSpace -> CTRL : GreenSpace

     deactivate GreenSpace

            CTRL -> UI : GreenSpace
     deactivate CTRL


     UI --> GSM : displays all data and operation success
     deactivate UI

@enduml
