@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
participant "RegisterGreenSpaceController" as CTRL
participant "Organization" as Organization
participant "greenSpace: \n GreenSpace" as GreenSpace

 CTRL -> Organization : registerGreenSpace(name, area, size, managerName)
            activate Organization
            Organization -> GreenSpace : registerGreenSpace(name, area, size, managerName)
            deactivate Organization

     activate GreenSpace

            GreenSpace -> CTRL : greenSpace

     deactivate GreenSpace



     deactivate CTRL

@enduml