@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

actor "Human Resources Manager" as HRM
actor "Vehicle Fleet Manager" as VFM

usecase "UC1 - As a Human Resources Manager (HRM), I want to register skills that a collaborator may have" as UC1
usecase "UC2 - As an HRM, I want to register a job that a collaborator need to have" as UC2
usecase "UC3 - As an HRM, I want to register a collaborator with a job and fundamental characteristics" as UC3
usecase "UC4 - As an HRM, I want to assign one or more skills to a collaborator" as UC4
usecase "UC5 - As a HRM, I want to generate a team proposal automatically" as UC5
usecase "UC6 - As an FM, I wish to register a vehicle including Brand, Model, Type, Tare, Gross Weight, Current Km, Register Date, Acquisition Date, Maintenance/Check-up Frequency (in Kms)" as UC6
usecase "UC7 - As an FM, I wish to register a vehicle’s check-up" as UC7
usecase "UC8 - As an FM, I want to list the vehicles needing the check-up" as UC8
HRM --> UC1
HRM --> UC2
HRM --> UC3
HRM --> UC4
HRM --> UC5
FM --> UC6
FM --> UC7
FM --> UC8



@enduml
