@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Skills {
    - String description

    + Skills(description)
}

class HRM {
}

class SkillsRepository {
    + getSkills()
}

class EmployeeRepository {
    + getOrganizationByEmployeeEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getSkillsRepository()
}

class SkillsController {
    + SkillsController( SkillsRepository)
    + getSkills()
    + createSkill (String skillName)
}

note bottom of SkillsRepository
    - used for accessing
    the skills
end note

class SkillsUI {
}

Repositories -> Repositories : instance

SkillsUI .> SkillsController

SkillsController .> Repositories : repositories

Repositories -> "1" SkillsRepository

SkillsController ..> Skills : jobs
SkillsController ..> EmployeeRepository : employeeRepository


Repositories --> "1" EmployeeRepository

EmployeeRepository --> "*" HRM

SkillsController ..> "1" HRM : manager
SkillsRepository "1" --> "*" Skills : jobs
HRM "1" --> "1..*" Skills : register

@enduml