    @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods
class Outside_User{
    name
    email
    password
}
class Portal{
    task category
}
class Malfunctions{}
class Flaws{}
class Comments{}
class Schedule{
    tasks
}
class Garden{
    description
}
class Medium_Sized{
    description
}
class Large_Sized{
    description
}
class Vehicles_Machines_Equipment{
    description
}
class FM{
}
class HRM{
}
class GSM{
}
class Green_Spaces{

}
class Team{
    collaborators
}

class Collaborators{
    competences
    profession
}
class Employees {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Task {
    reference
    description
    informalDesc
    technicalDesc
    duration
    cost
}
class Managers {
    name
    email
    position
    phone
}
class Organization{

}
'Platform "1" -- "*" Organization : has registered >
'Platform "1" -- "*" Category : defines >
Organization "1" - "1..*" Employees : has >
Employees "1" - "0..*" Collaborators: are >
'Task "*" -- "1" Employees: created by >
Employees "1" -- "*" Managers : are >
Collaborators -- Team : make >
Team -- Task : attributed <
Task -- Green_Spaces:  >
Managers "1" -- GSM: has >
Managers "1" -- HRM: has >
Managers "1" -- FM: has >
Managers -- Team: creates >
Managers -- Green_Spaces: manages >
Green_Spaces -- Garden: has >
Green_Spaces -- Medium_Sized: has >
Green_Spaces -- Large_Sized: has >
Vehicles_Machines_Equipment -- Team: are attributed to >
Managers -- Collaborators: hire and register >
Organization "1"-- Vehicles_Machines_Equipment: have >
Managers -- Vehicles_Machines_Equipment: choose >
Malfunctions "1"-- "*"Task:creates >
Flaws "*" -- "*" Task : creates >
Green_Spaces "1..*" -- "*"Task:>
Task "*" -- Schedule : goes to >
Schedule "1" -- Managers: is managed by >
Outside_User "1" -- "1" Portal : reports >
Portal "1" -- Malfunctions:>
Portal "1" -- Flaws:>
Portal "1" -- Comments:>

@enduml