    @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}
class Portal{
    comments
    malfunctions
    task category
}
class Agenda{
    tasks
}
class Garden{
    description
}
class Medium_Sized{
    description
}
class Large_Sized{
    description
}
class Vehicles_Machines_Equipment{
    description
}
class FM{
}
class HRM{
}
class GSM{
}
class Green_Spaces{

}
class Team{
    Collaborators
}

class Collaborators{
    competences
    profession
}
class Employees {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Task {
    reference
    description
    informalDesc
    technicalDesc
    duration
    cost
}
class Managers {
    name
    email
    position
    phone
}
class User {
    name
    email
    password
}
class Organization{

}
'Platform "1" -- "*" Organization : has registered >
'Platform "1" -- "*" Category : defines >
Organization "1" - "0..*" Employees : has >
Employees "1" - "0..*" Collaborators: are >
'Task "*" -- "1" Employees: created by >
Employees "1" -- "*" Managers : are >
'Employees "0..1" -- "1" User: acts as >
Collaborators -- Team : make >
Team -- Task :  >
Task -- Green_Spaces:  >
Managers -- GSM: has >
Managers -- HRM: has >
Managers -- FM: has >
Managers -- Team: creates >
Managers -- Green_Spaces: manages >
Green_Spaces -- Garden: has >
Green_Spaces -- Medium_Sized: has >
Green_Spaces -- Large_Sized: has >
Vehicles_Machines_Equipment -- Team: are attributed to >
Managers -- Collaborators: hire and register >
Organization -- Vehicles_Machines_Equipment: have >
Managers -- Vehicles_Machines_Equipment: choose >
Organization -- Agenda: has >
Agenda -- Managers: help >
Portal -- Organization: reports >
User -- Portal: uses >
User -- Employees: are <



@enduml