@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant "AgendaUI" as UI
participant "AgendaController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as organizationRepository
participant "organization:\n Organization" as Organization
participant "ToDoList: \n ToDoList" as TDL
participant "Agenda: \n Agenda" as Agenda

activate GSM

     GSM -> UI : asks to add a new entry to the Agenda

     activate UI

            UI -> GSM : asks to select the To-Do List entry
            GSM -> UI : selects the To-Do List entry
            UI -> GSM : asks to type the intended date
            GSM -> UI : selects the intended date
            UI -> CTRL : creates

     activate CTRL

            CTRL -> Rep : getInstance()

     activate Rep

            Rep -> CTRL : repositories

     deactivate Rep

            CTRL -> organizationRepository : getOrganizationRepository()

     activate organizationRepository

            organizationRepository -> CTRL : organizationRepository

     deactivate organizationRepository

            CTRL -> Organization : getManager()

     activate Organization

            Organization -> CTRL : Manager



            Organization -> Rep : getToDoList()
     deactivate Organization

     activate GreenSpace

            GreenSpace -> CTRL : GreenSpace

     deactivate GreenSpace

            CTRL -> UI : GreenSpace
     deactivate CTRL


     UI --> GSM : displays all data and operation success
     deactivate UI

@enduml
