@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant "ToDoListUI" as UI
participant "ToDoListController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as organizationRepository
participant "Entry: \n entry" as entry
participant "ToDoList: \n ToDoList" as toDoList

activate GSM

     GSM -> UI : asks to register a new entry

     activate UI

            UI -> GSM : requests a name
            GSM -> UI : types name
            UI -> GSM : request urgency
            GSM -> UI : selects urgency
            UI -> GSM : requests duration
            GSM -> UI : types duration
            UI -> CTRL** : create


     activate CTRL

            CTRL -> Rep : getInstance()

     activate Rep

            Rep -> CTRL : repositories

     deactivate Rep

            CTRL -> organizationRepository : getOrganizationRepository()

     activate organizationRepository

            organizationRepository -> CTRL : organizationRepository

     deactivate organizationRepository

            CTRL -> entry : registerEntry (String task, Urgency urgency, int duration, GreenSpace greenSpace, Status status)

     activate entry

            entry -> toDoList : addEntry(Entry entry)

     activate toDoList

            toDoList -> entry : entry

     deactivate toDoList

            entry -> CTRL : entry

     deactivate entry

            CTRL -> UI : entry

     deactivate CTRL

     UI --> GSM : displays all data and operation success

     deactivate UI

@enduml
