@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Organization{

}

class ToDoListUI{

}


class ToDoListController{

}

class Repositories{
    - Repositories()
    + getInstance() : Repositories
    + getToDoList()
}

class Entry{
    -Task
    -Urgency
    -Status
    -Duration
    -Green space
}

ToDoListUI .right-> ToDoListController
ToDoListController -right-> Organization
Organization -down-> Entry: Register entry
OrganizationRepository -down-> Organization
ToDoListController -.down-> Repositories : repositories
Repositories -down-> "1" OrganizationRepository
@enduml
