@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Managers {
    name
    position
    phoneNumber
    email
}

class Job{
    name
}
class HRM{

}

'Platform "1" -- "*" Organization : has registered >
Managers "1" - "0..*" HRM: has >
'Task "*" -- "1" Employee: created by >
Managers "1" -- "0..*" Job : registers >
'Employee "0..1" -- "1" User: acts as >
@enduml