@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

class Vehicle {
  Brand
  Model
  Type
  Tare
  Current Km
  Register Date
}

class CheckUp {
  Date
  Updated Kilometers
  Check-up Results
}

class FleetManager {

}

class Managers {
    name
    email
    position
    phone
}
Managers "1" -- "1" CheckUp : register >
Managers "1" -- "1" FleetManager : have >
Vehicle "1" -- "0..*" CheckUp : has >
Vehicle "1" -- "1" CheckUp : has <
Managers "1" -- "0..*" Vehicle : manages >

@enduml