@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

class Vehicles_Machines_Equipment {
  description
}

class CheckUp {
  date
}

class FleetManager {

}

class Managers {
    name
    email
    position
    phone
}
Managers "1" -- "1" CheckUp : register >
Managers "1" -- "1" FleetManager : has >
Vehicles_Machines_Equipment "1" -- "1" CheckUp : has <

@enduml