@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : Asks to cancel an entry from the Agenda
    activate System
        System --> GSM : Retrieve list of entries and requests to choose one
    deactivate System
    GSM -> System : Chooses one of the entries
    activate System
        System --> GSM : Displays operation success
    deactivate System


@enduml