@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "FM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Request to register vehicles check-up
    activate System

        System --> Employee : Display vehicle selection interface
    deactivate System

    Employee -> System : Select vehicle
    activate System

        System --> Employee : Display Vehicle details
    deactivate System

    Employee -> System : Enter check-up result
    activate System

        System --> Employee :  Confirmation of check-up result registration
    deactivate System

@enduml