@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model


class Managers {
    name
    email
    position
    phone
}
class HRM{
}
class New_Collaborators{
    name
    birthdate
    admission date
    address
    contact info (mobile and email)
    ID doc type
    ID number
}
Managers "1" -- "1" New_Collaborators : register >
Managers "1" -- "1" HRM : have >

@enduml