@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "SkillsRepository:\nSkillsRepository" as SkillsRepository
participant "JobRepository:\nJobRepository" as JobRepository


activate ADM

        ADM -> UI : asks to register a collaborator with a profession and key attributes

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getCollaboratorRepository()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getCollaboratorRepository()
                activate PLAT

                    PLAT --> CTRL: collaboratorRepository
                deactivate PLAT

                CTRL -> CollaboratorRepository : getCollaboratorRecord()
                activate CollaboratorRepository

                    CollaboratorRepository --> CTRL : collaboratorRecord
                deactivate CollaboratorRepository


                CTRL --> UI : CollaboratorRecord
            deactivate CTRL

            UI --> ADM : requests data (a collaborator)
                    deactivate UI

                ADM -> UI : types requested data (a collaborator, a profession and key atributes)
        activate UI

    UI -> CTRL : getSkills()
                activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getSkillsRepository()
                    activate PLAT

                        PLAT --> CTRL: SkillsRepository
                    deactivate PLAT

                    CTRL -> SkillsRepository : getSkills()
                    activate SkillsRepository

                        SkillsRepository --> CTRL : SkillsList
                    deactivate SkillsRepository


                    CTRL --> UI : SkillsList
                deactivate CTRL
                        UI -> ADM : asks to select a set of skills
    deactivate UI
                            ADM -> UI : selects the intended skills
            activate UI

        UI -> CTRL : getJobs()
                    activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                        activate RepositorySingleton

                            RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                        CTRL -> PLAT : getJobRepository()
                        activate PLAT

                            PLAT --> CTRL: JobRepository
                        deactivate PLAT

                        CTRL -> JobRepository : getJobs()
                        activate JobRepository

                            JobRepository --> CTRL : JobsList
                        deactivate JobRepository


                        CTRL --> UI : JobsList
                    deactivate CTRL
                        UI -> ADM : asks to select a job

        deactivate UI
                                    ADM -> UI : selects a Job
            activate UI
             UI -> CTRL : getCollaboratorRepository()
                        activate CTRL

                            CTRL -> RepositorySingleton : getInstance()
                            activate RepositorySingleton

                                RepositorySingleton --> CTRL: repositories
                            deactivate RepositorySingleton

                            CTRL -> PLAT : getCollaboratorRepository()
                            activate PLAT

                                PLAT --> CTRL: collaboratorRepository
                            deactivate PLAT

                            CTRL -> CollaboratorRepository : setCollaboratorRecord()
                            activate CollaboratorRepository

                                CollaboratorRepository --> CTRL : collaboratorRecord
                            deactivate CollaboratorRepository


                            CTRL --> UI : CollaboratorRecord
                        deactivate CTRL
                                UI --> ADM : shows all data and displays operation success
deactivate UI

@enduml