@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative two

autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : requests to create a new team
    activate System

        System --> Employee : requests number of team members
    deactivate System

    Employee -> System : specifies number of team members
    activate System

        System -> Employee : requests skills needed
    deactivate System

    Employee -> System : specifies skills needed
    activate System



       alt Team generated accepted
        System --> Employee : generates team proposal
        deactivate System
            Employee -> System : approves team proposal
            activate System
            System --> Employee : confirms team creation

       else Team generated rejected
            System --> Employee : generates team proposal
               deactivate System
             Employee -> System : rejects team proposal
             activate System
             System --> Employee : deletes team creation
        else Team not generated
            System --> Employee : displays error message

        end
    deactivate System
@enduml
