@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant "PostponeEntryUI" as UI
participant "AgendaController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as organizationRepository
participant "agendaRepository: \n AgendaRepository" as Agenda

activate GSM

     GSM -> UI : asks to postpone an entry in the Agenda

     activate UI

            UI -> GSM : asks to select the Agenda entry
            UI -> CTRL** : create

     activate CTRL
            CTRL -> Rep : getInstance()
     activate Rep

                      Rep -> CTRL : repositories

               deactivate Rep

                      CTRL -> organizationRepository : getOrganizationRepository()

               activate organizationRepository

                      organizationRepository -> CTRL : organizationRepository

               deactivate organizationRepository

                      CTRL -> Agenda : getAgendaRepository()

               activate Agenda

                      Agenda -> CTRL : agenda

               deactivate Agenda

                      CTRL -> UI : agenda
                      UI -> GSM : asks to select the Agenda entry
                      GSM -> UI : selects the Agenda entry
                      UI -> GSM : asks to type the intended date
                      GSM -> UI : selects the intended date
                      UI -> CTRL : entry
                      CTRL -> Agenda : getAgendaRepository()
               activate Agenda

                      Agenda -> Agenda: addEntry(Entry entry)

                 Agenda -> CTRL : entry

          deactivate Agenda

                 CTRL -> UI : entry

          deactivate CTRL

          UI --> GSM : displays all data and operation success

          deactivate UI

@enduml
