@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant "CancelEntryUI" as UI
participant "AgendaController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as organizationRepository
participant "Organization" as or
participant "agendaRepository: \n AgendaRepository" as Agenda
participant "Entry" as Entry
participant "Status" as Status

activate GSM

         GSM -> UI : asks to cancel an entry in the Agenda

     activate UI

        UI -> CTRL** : create

     activate CTRL

            CTRL -> Rep : getInstance()

     activate Rep

                      Rep -> CTRL : repositories

               deactivate Rep

                      CTRL -> organizationRepository : getOrganizationRepository()

               activate organizationRepository

                      organizationRepository -> CTRL : organizationRepository

               deactivate organizationRepository

                      CTRL -> Agenda : getAgendaRepository()

               activate Agenda

                      Agenda -> CTRL : agenda

               deactivate Agenda

                      CTRL -> UI : agenda
                      UI -> GSM : asks to select the Agenda entry
                      GSM -> UI : selects the Agenda entry
                      UI -> CTRL : entry
                      CTRL -> Entry : entry
               activate "Entry"

                      Entry -> "Status"  :  Entry.setStatus(Status.canceled)

                activate "Status"

                         "Status" -> Entry : entry

                 deactivate "Status"

                 Entry -> CTRL : entry

          deactivate "Entry"


                         CTRL -> or : entry
          activate or

                          or -> Agenda : add(entry)
          activate Agenda

                          Agenda -> or : entry

            deactivate Agenda

                          or -> CTRL : entry

            deactivate or

                 CTRL -> UI : entry

          deactivate CTRL

          UI --> GSM : displays all data and operation success

          deactivate UI

@enduml
