@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

class SkillRepository {
    + getSkillsByNames(skills)
}

class GenerateTeamProposalController {
    + GenerateTeamProposalController(collaboratorRepository, skillRepository)
    + generateTeamProposal(maxTeamSize, skills)
    - getCollaboratorsBySkills(skills)
    - generateTeamProposals(maxTeamSize, collaborators)
}

class GenerateTeamProposalUI {
}

class CollaboratorRepository {
    + getCollaboratorsBySkills(skills)
}

class Collaborator {
    -name
    -List<Skill> skillList
    + assignSkill(collaboratorName, skillName)
    +validateSkill(skillName)
    }

class Skill {
    -skillName
    }

class TeamProposal {
    -List<Collaborator> teamMembers
    + getTeamMembers()
    + addTeamMember(collaborator)
    + removeTeamMember(collaborator)
}

GenerateTeamProposalUI .> GenerateTeamProposalController

GenerateTeamProposalController ..> "1" Skill : skill
GenerateTeamProposalController ..> "1" CollaboratorRepository : collaboratorRepository
CollaboratorRepository --> "*" Collaborator
GenerateTeamProposalController ..> "1" SkillRepository : skillRepository

GenerateTeamProposalController ..> "1" TeamProposal : teamProposal
TeamProposal "has"--> "*" Collaborator
Collaborator "has"--> "*" Skill

SkillRepository --> "*" Skill

@enduml