@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as ADM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillsRepository:\nSkillsRepository" as SkillsRepository
participant "jobsRepository:\nJobsRepository" as JobsRepository
participant "collaboratorRecordRepository:\nCollaboratorRecordRepository" as CollaboratorRecordRepository


activate ADM

        ADM -> UI : asks to register a collaborator with a profession and key attributes

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getcollaboratorRecord()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getCollaboratorRecordRepository()
                activate PLAT

                    PLAT --> CTRL: collaboratorRecordRepository
                deactivate PLAT

                CTRL -> CollaboratorRecordRepository : getCollaboratorRecord()
                activate CollaboratorRecordRepository

                    CollaboratorRecordRepository --> CTRL : collaboratorRecord
                deactivate CollaboratorRecordRepository


                CTRL --> UI : CollaboratorRecord
            deactivate CTRL

            UI --> ADM : requests data (a collaborator)
        deactivate UI

    ADM -> UI : types requested data (a collaborator, a profession and key atributes)
    activate UI
    UI -> CTRL : getSkills()
                activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getSkillsRepository()
                    activate PLAT

                        PLAT --> CTRL: SkillsRepository
                    deactivate PLAT

                    CTRL -> SkillsRepository : getSkills()
                    activate SkillsRepository

                        SkillsRepository --> CTRL : SkillsList
                    deactivate SkillsRepository


                    CTRL --> UI : SkillsList
                deactivate CTRL

        UI --> ADM : asks to select a set of skills
    deactivate UI

    ADM -> UI : selects the intended skills
    activate UI
        UI -> CTRL : getJobs()
                    activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                        activate RepositorySingleton

                            RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                        CTRL -> PLAT : getJobsRepository()
                        activate PLAT

                            PLAT --> CTRL: JobsRepository
                        deactivate PLAT

                        CTRL -> JobsRepository : getJobs()
                        activate JobsRepository

                            JobsRepository --> CTRL : JobsList
                        deactivate JobsRepository


                        CTRL --> UI : JobsList
                    deactivate CTRL

            UI --> ADM : ask to select a job
        deactivate UI
        ADM -> UI : selects the intended job
        activate UI
        UI -> CTRL : getcollaboratorRecord()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getCollaboratorRecordRepository()
                activate PLAT

                    PLAT --> CTRL: collaboratorRecordRepository
                deactivate PLAT

                CTRL -> CollaboratorRecordRepository : setCollaboratorRecord()
                activate CollaboratorRecordRepository

                    CollaboratorRecordRepository --> CTRL : collaboratorRecord
                deactivate CollaboratorRecordRepository


                CTRL --> UI : CollaboratorRecord
            deactivate CTRL

            UI --> ADM : displays all data and operation success
        deactivate UI




deactivate ADM

@enduml