@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillsRepository:\nSkillsRepository" as SkillsRepository
participant "jobsRepository:\nJobsRepository" as JobsRepository
participant "collaboratorRecordRepository:\nCollaboratorRecordRepository" as CollaboratorRecordRepository


activate ADM

        ADM -> UI : asks to register a collaborator with a profession and key attributes

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getcollaboratorRecord()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getCollaboratorRecordRepository()
                activate PLAT

                    PLAT --> CTRL: collaboratorRecordRepository
                deactivate PLAT

                CTRL -> CollaboratorRecordRepository : getCollaboratorRecord()
                activate CollaboratorRecordRepository

                    CollaboratorRecordRepository --> CTRL : collaboratorRecord
                deactivate CollaboratorRecordRepository


                CTRL --> UI : CollaboratorRecord
            deactivate CTRL

            UI --> ADM : requests data (a collaborator)
        deactivate UI

    ADM -> UI : types requested data (a collaborator, a profession and key atributes)
    activate UI
    UI -> CTRL : getSkills()
                activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getSkillsRepository()
                    activate PLAT

                        PLAT --> CTRL: SkillsRepository
                    deactivate PLAT

                    CTRL -> CollaboratorRecordRepository : getSkills()
                    activate CollaboratorRecordRepository

                        CollaboratorRecordRepository --> CTRL : SkillsList
                    deactivate CollaboratorRecordRepository


                    CTRL --> UI : SkillsList
                deactivate CTRL

        UI --> ADM : asks to select a set of skills
    deactivate UI

    ADM -> UI : selects the intended skills
    activate UI

        UI --> ADM : ask to select a job
    deactivate UI

    ADM -> UI : selects the intended job
    activate UI

        UI -> CTRL : registerCollaborator(new collabporator required info)
        activate CTRL

            CTRL -> CTRL : setCollaboratorByDescription(new collaborator required info)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : setColllaboratorToRecordRepository()
                activate PLAT

                    PLAT -> CTRL : collaboratorRecordRepository
                deactivate PLAT

                CTRL -> CollaboratorRecordRepository : setCollaboratorByDescription(new collaborator required info)
                activate CollaboratorRecordRepository

                    CollaboratorRecordRepository --> CTRL : collaboratorRecord
                deactivate CollaboratorRecordRepository
                    CTRL --> CTRL : collaboratorRecord
            deactivate CTRL

            |||
            CTRL -> CTRL : getCollaboratorFromSession()
            activate CTRL

                CTRL -> _APP: getInstance()
                activate _APP
                    _APP -> CTRL: appSession
                deactivate _APP


                CTRL -> APP: getCurrentSession()
                activate APP

                    APP --> CTRL: currentSession
                deactivate APP

                CTRL -> SESSAO: email = getUserEmail()
                activate SESSAO

                    SESSAO --> CTRL: email
                deactivate SESSAO


                CTRL -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> CTRL: organizationRepository
                deactivate PLAT


                CTRL -> OrganizationRepository: getOrganizationByEmployeeEmail(email)
                activate OrganizationRepository

                    loop [for each organization
                        OrganizationRepository -> ORG : anyEmployeeHasEmail(email)
                        activate ORG

                             ORG --> OrganizationRepository : true/false
                        deactivate ORG
                    end
                    OrganizationRepository --> CTRL : organization
                deactivate OrganizationRepository

                CTRL -> ORG: getEmployeeByEmail(email)
                activate ORG

                    ORG --> CTRL : employee
                deactivate ORG

                CTRL --> CTRL : employee
            deactivate CTRL

            |||
            CTRL -> ORG: registerCollaborator(employee required (new employee required info))
            activate ORG

                ORG -> EMPLOYEE**: register(new collaborator (collaborator required info))
                ORG -> ORG: addCollaborator (new collaborator))


                activate ORG
                    ORG -> ORG: validateRegistration(task)
                    activate ORG
                        ORG --> ORG
                    deactivate ORG

                    ORG --> ORG
                deactivate ORG

                ORG --> CTRL : task

            deactivate ORG

            CTRL --> UI: resgistration
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml