@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager" as GSM
participant ":AssignVehicleToEntryUI" as UI
participant ":AssignVehicleToEntryCTRL" as CTRL
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "agendaRepository:\nAgendaRepository" as AgendaRepository
participant "organization:\nOrganization" as Org
participant "organizationRepository:\nOrganizationRepository" as OrgRepository
participant "vehicle:\nVehicle" as Vehicle
participant "entry:\nEntry" as Entry

activate GSM
    GSM -> UI : Wants to assign vehicles to entry
    activate UI
        UI --> CTRL** : create
        UI -> CTRL : getVehicles()
        activate CTRL
            CTRL -> VehicleRepository : getVehicles()
                activate VehicleRepository
                    VehicleRepository --> CTRL : Vehicles
                deactivate VehicleRepository
        CTRL --> UI : Vehicles
        deactivate CTRL
        UI -> GSM : shows vehicles
        deactivate UI
        GSM -> UI : selects vehicles
        activate UI
        UI --> UI : keepVehicles(selectedVehicles)
        UI -> CTRL : getEntries()

      activate CTRL
                  CTRL -> AgendaRepository : getEntries()
                      activate AgendaRepository
                          AgendaRepository --> CTRL : Entries
                      deactivate AgendaRepository


              CTRL --> UI : Entries
              deactivate CTRL

        UI -> GSM : shows entries
        deactivate UI
        GSM -> UI : selects entry
        activate UI
        UI --> UI : keepEntry(selectedEntry)
        UI -> CTRL : attributeVehiclesToEntry(selectedVehicles, selectedEntry)
        activate CTRL
            CTRL -> OrgRepository : getOrganization()
                activate OrgRepository
                    OrgRepository --> CTRL : Organization
                deactivate OrgRepository


            CTRL -> Org : setVehicles(selectedVehicles)
            activate Org
            Org --> Entry : setVehicles(selectedVehicles)
            deactivate Org
            activate Entry
            Entry --> CTRL : Entry updatedEntry
            deactivate Entry

        CTRL --> UI : (In)Success and updatedEntry

        deactivate CTRL

        UI-> GSM : Displays (In)Success and updatedEntry
    deactivate UI
deactivate GSM
@enduml