@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":GreenSpaceListController" as CTRL
participant "Interface" as Interface
participant "Repositories" as Rep
participant "repositories:\nRepositories" as Repositories
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "Organization:\norganization" as org
participant "greenSpace:\ngreenSpace" as GreenSpace
participant "Config" as Config


-> CTRL : getGreenSpacesByName()
        activate CTRL
         group get GreenSpaces by name

            CTRL -> Rep : getInstance()
            activate Rep

                Rep --> CTRL : repositories
            deactivate Rep

            CTRL -> Repositories : getManagerName()
            activate Repositories

                Repositories --> CTRL : ManagerName
            deactivate Repositories

            CTRL -> OrganizationRepository : getManagerName()
            activate OrganizationRepository

                OrganizationRepository -> org : getManagerName()
                activate org

                    org --> OrganizationRepository : ManagerName
                deactivate org

                OrganizationRepository -> CTRL : ManagerName
            deactivate OrganizationRepository

            CTRL -> Repositories : getGreenSpaces()
            activate Repositories

                Repositories --> CTRL : GreenSpaces
            deactivate Repositories

            CTRL -> GreenSpaceRepository : getGreenSpaces()
            activate GreenSpaceRepository

                GreenSpaceRepository -> GreenSpace : getGreenSpace()
                activate GreenSpace

                    GreenSpace --> GreenSpaceRepository : greenSpace
                deactivate GreenSpace
                GreenSpaceRepository --> CTRL : greenSpaces
            deactivate GreenSpaceRepository

            CTRL --> Interface : sortGreenSpaces()
            activate Interface

                Interface -> Config : getSortingAlgorithm()
                activate Config

                    Config --> Interface : sortingAlgorithm
                deactivate Config

                Interface --> CTRL : sortedGreenSpaces
            deactivate Interface
         end
           <-- CTRL : greenSpacesByName
        deactivate CTRL



@enduml
