@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as VFM
participant ":GreenSpaceManegementUI" as UI
participant ":GreenSpaceController" as CTRL
participant "UserSession" as usersession
participant "Repositories" as Rep
participant "repositories:\nRepositories" as Repositories
participant "managerRepository:\nManagerRepository" as VehicleRepository
participant "manager:\nManager" as Vehicle
participant "greenSpaceRepository:\nGreenSpaceRepository" as greenSpaceRepository

activate VFM

VFM -> UI : Request to list all managed green spaces

    activate UI

        UI -> CTRL** : create

        UI -> usersession : getUserEmail()
               activate usersession

        usersession --> UI : UserEmail
        deactivate usersession


        UI -> CTRL : getlistManagedGreenSpaces(userEmail)
        activate CTRL

            CTRL -> Rep : getInstance()
            activate Rep

                Rep --> CTRL : repositories
            deactivate Rep

            CTRL -> Repositories : getGreenSpaceRepository()
            activate Repositories

            Repositories --> CTRL : greenSpaceRepository
            deactivate Repositories


            CTRL -> Repositories : getManagerRepository()
            activate Repositories

                Repositories --> CTRL : managerRepository
            deactivate Repositories

            CTRL -> VehicleRepository : findByEmail()
                        activate VehicleRepository

                            VehicleRepository --> CTRL : manager
                        deactivate VehicleRepository

            CTRL -> Vehicle : getGreenSpaceManaged()
                                    activate Vehicle

                                        Vehicle --> CTRL : greenSpaceList
                                    deactivate Vehicle

             CTRL -> "greenSpaceRepository:\nGreenSpaceRepository" : findGreenSpacesByManager()
                                                activate "greenSpaceRepository:\nGreenSpaceRepository"

                                                    "greenSpaceRepository:\nGreenSpaceRepository" --> CTRL : greenSpaceList
                                                deactivate "greenSpaceRepository:\nGreenSpaceRepository"




            CTRL --> UI : VehiclesNeedingCheckUp
        deactivate CTRL

        UI --> VFM : Retrieve list of green spaces

    deactivate UI
VFM -> UI : Chooses green spaces managed by GSM
UI --> VFM : Confirmation of the operation

deactivate VFM

@enduml
