@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant ":GreenSpaceListUI" as UI
participant ":GreenSpaceListController" as CTRL
participant "Repositories" as Rep
participant "repositories:\nRepositories" as Repositories
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "Organization:\norganization" as org
participant "greenSpace:\ngreenSpace" as GreenSpace

activate GSM

GSM -> UI : Request to list all managed green spaces

    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getGreenSpacesByName()
        activate CTRL

            CTRL -> Rep : getInstance()
            activate Rep

                Rep --> CTRL : repositories
            deactivate Rep

            CTRL -> Repositories : getManagerName()
            activate Repositories

                Repositories --> CTRL : ManagerName
            deactivate Repositories

            CTRL -> OrganizationRepository : getManagerName()
            activate OrganizationRepository

                OrganizationRepository -> org : getManagerName()
                activate org

                    org --> OrganizationRepository : ManagerName
                deactivate org

                OrganizationRepository -> CTRL : ManagerName
            deactivate OrganizationRepository

            CTRL -> Repositories : getGreenSpaces()
            activate Repositories

                Repositories --> CTRL : GreenSpaces
            deactivate Repositories

            CTRL -> GreenSpaceRepository : getGreenSpaces()
            activate GreenSpaceRepository

                GreenSpaceRepository -> GreenSpace : getGreenSpace()
                activate GreenSpace

                    GreenSpace --> GreenSpaceRepository : greenSpace
                deactivate GreenSpace
                GreenSpaceRepository --> CTRL : greenSpaces
            deactivate GreenSpaceRepository

            CTRL --> UI : greenSpacesByName
        deactivate CTRL

        UI --> GSM : Retrieve list of green spaces managed by the GSM
    deactivate UI
deactivate GSM

@enduml
