@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as GSM
participant ":GreenSpaceListUI" as UI
participant ":GreenSpaceListController" as CTRL

activate GSM

GSM -> UI : Request to list all managed green spaces

    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getGreenSpacesByName()
        activate CTRL

            ref over CTRL
                Get GreenSpaces by name
            end

            CTRL --> UI : greenSpacesByName
        deactivate CTRL

        UI --> GSM : Retrieve list of green spaces managed by the GSM
    deactivate UI
deactivate GSM

@enduml
