@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as VFM
participant ":GreenSpaceListUI" as UI
participant ":GreenSpaceListController" as CTRL
participant "Repositories" as Rep
participant "repositories:\nRepositories" as Repositories
participant "greenSpaceRepository:\nGreenSpaceRepository" as VehicleRepository
participant "greenSpace:\ngreenSpace" as Vehicle


activate VFM

VFM -> UI : Request to list all managed green spaces

    activate UI

        UI -> CTRL** : create

        UI -> usersession : getUserEmail()
               activate usersession

        usersession --> UI : UserEmail
        deactivate usersession


        UI -> CTRL : getlistManagedGreenSpaces(userEmail)
        activate CTRL

            CTRL -> Rep : getInstance()
            activate Rep

                Rep --> CTRL : repositories
            deactivate Rep

            CTRL -> Repositories : getGreenSpaceRepository()
            activate Repositories

            Repositories --> CTRL : greenSpaceRepository
            deactivate Repositories


            CTRL -> Repositories : getManagerRepository()
            activate Repositories

                Repositories --> CTRL : managerRepository
            deactivate Repositories

            CTRL -> VehicleRepository : findByEmail()
                        activate VehicleRepository

                            VehicleRepository --> CTRL : manager
                        deactivate VehicleRepository

            CTRL -> Vehicle : getGreenSpaceManaged(manager)
                                    activate Vehicle

                                        Vehicle --> CTRL : greenSpaceList
                                    deactivate Vehicle

             CTRL -> "greenSpaceRepository" : findGreenSpacesByManager()
                                                activate "greenSpaceRepository"

                                                    "greenSpaceRepository" --> CTRL : greenSpaceList
                                                deactivate "greenSpaceRepository"




            CTRL --> UI : VehiclesNeedingCheckUp
        deactivate CTRL

        UI --> VFM : Retrieve list of green spaces



VFM -> UI : Chooses green spaces managed by GSM


 UI -> CTRL : confirmSelection(selectedGreenSpaces)
        activate CTRL

        CTRL -> "greenSpaceRepository" : updateSelectedGreenSpaces(selectedGreenSpaces)
                                                        activate "greenSpaceRepository"

                                                            "greenSpaceRepository" --> CTRL : Confirmation of the operation
                                                        deactivate "greenSpaceRepository"



         CTRL --> UI : Confirmation of the operation
                deactivate CTRL


UI --> VFM : Confirmation of the operation

VFM --> UI : Confirms that he want to creat the list

    UI --> CTRL : getGreenSpaceList(greenSpaceManager)
    activate CTRL

        CTRL --> Rep : getInstance()
        activate Rep

        Rep --> CTRL : repositories
        deactivate Rep



    CTRL --> UI :
    deactivate CTRL


UI --> VFM : Show the list

deactivate UI
deactivate VFM

@enduml
