@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class GreenSpaceListUI{

}

class GreenSpaceListController{

}

class Organization{

}

class GreenSpace{

}

class Repositories{

}

class GreenSpaceRepository{

}

class OrganizationRepository{

}


GreenSpaceListUI .> GreenSpaceListController
GreenSpaceListController ..> Organization
Organization --> GreenSpace
GreenSpaceListController .> Repositories
Repositories --> GreenSpaceRepository
Organization <- GreenSpaceRepository
Repositories --> OrganizationRepository
Organization <- OrganizationRepository

@enduml