@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US023

autonumber

actor "Green Space Manager" as GSM
participant ":System" as System

activate GSM
    GSM -> System : Request to assign team to entry
    activate System
        System --> GSM : Retrieves list of teams
    deactivate System
    GSM -> System : Selects team
    activate System
        System --> GSM: Retrieves list of entries
    deactivate System
    GSM -> System : Selects entry
    activate System
        System --> GSM: Displays success or failure message
    deactivate System
deactivate GSM
@enduml