@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as ADM
participant ":GreenSpaceListUI" as UI
participant ":GreenSpaceListController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "GreenSpace:\n greenSpace" as GreenSpace
participant "Organization:\n organization" as Organization
activate ADM

    ADM -> UI : Request to list all green spaces managed by him

    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getGreenSpacesByName()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getGreenSpacesByName()
            activate PLAT

                PLAT --> CTRL: GreenSpaceByName
            deactivate PLAT

            CTRL -> GreenSpaceRepository : getGreenSpacesByName()
            activate GreenSpaceRepository

                GreenSpaceRepository -> GreenSpace: getGreenSpaceByName()
                activate GreenSpace

                    GreenSpace -> Organization: getManagerName()
                    activate Organization

                        Organization --> GreenSpace: managerName
                    deactivate Organization

                    GreenSpace --> GreenSpaceRepository : GreenSpaceByName
                deactivate GreenSpace
                GreenSpaceRepository --> CTRL : GreenSpacesByName
            deactivate GreenSpaceRepository


            CTRL --> UI : GreenSpaceByName
        deactivate CTRL

        UI --> ADM : Retrieves list of green spaces managed by the GSM
    deactivate UI


deactivate ADM

@enduml