@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class FM {

}

class Managers {
    name
    email
    position
    phone
}


class Vehicles_Machines_Equipment {
    plate
    brand
    model
    type
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    maintenanceFrequency
}

'class User {
'    name
'    email
'    password
'}

'Platform "1" -- "*" FM : has registered >

Managers "1"-- "*"Vehicles_Machines_Equipment: register and choose >

Managers "1" -- "1"FM: has >


@enduml