@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":CompletionTaskController" as CTRL
participant ":Repositories" as Repositories
participant "repositories\n:Repositories" as REP
participant "organizationRepository\n:OrganizationRepository" as OrganizationRepository
participant "agendaRepository\n:AgendaRepository" as Agenda
participant "Organization\n:organization" as Organization
participant "entry:\nEntry" as Entry
participant "Status:\nstatus" as Status





        -> CTRL : setStatus()
        activate CTRL
group Set Status
            CTRL -> REP: setStatus()
            activate REP

                REP --> CTRL : status
            deactivate REP

            CTRL -> Agenda : setStatus()
            activate Agenda

                Agenda -> Entry : setStatus()
                activate Entry

                    Entry -> Status : setStatus()
                    activate Status

                        Status --> Entry : status
                    deactivate Status

                    Entry --> Agenda : status
                deactivate Entry

                Agenda --> CTRL : status
            deactivate Agenda
end
             <-- CTRL : status
        deactivate CTRL




@enduml
