@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as EMP
participant ":CompletionTaskUI" as UI
participant ":CompletionTaskController" as CTRL
participant "Repositories" as Rep
participant "organizationRepository:\nOrganizationRepository" as Repositories
participant "Agenda:\nAgenda" as Agenda
participant "entry:\nEntry" as Entry

activate EMP

    EMP -> UI : Requests to record the completion of a task
    activate UI

        UI -> CTRL** : create

        UI -> CTRL :
        UI --> EMP : Retrieves task list
    deactivate UI

    EMP -> UI : Chooses task to record completion
    activate UI

        UI --> EMP : Confirmation of the operation
    deactivate UI



@enduml
