@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative one

autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new team
    activate System

        System --> Employee : requests number of team members
    deactivate System

    Employee -> System : types requested number of team members
    activate System

    System -> Employee : requests skills needed
    deactivate System

    Employee -> System : types skills needed

    activate System

        System --> Employee : shows team created
    deactivate System


    Employee -> System : accepts data
    activate System

        System --> Employee : displays that the team was accepted
    deactivate System
@enduml